  
- hosts: master
  roles:
          - role: kubeadm-docker-role

- hosts: slave
  vars_prompt:
          - name: join
            prompt: "Please enter the command to join worker node with master"
            private: no
  roles:
          - role: kubeadm-docker-with-worker-role
